### ISSUE TITLE
[ED] OpenTapioca

### ISSUE THREAD

**Issue by hashpad** [kmdn/combining-linking-techniques#19]

**Comment by kmdn** [comment]
To create OpenTapioca ED-stand-alone:

1. Use OpenTapioca's CG System with scores.
2. Use the passed candidates and do an intersect with OpenTapioca's candidates.
3. Take the top-scored score(s) for each mention.
4. Profit. (aka. we now have succeeded in having a stand-alone ED based on a CG+EG thanks to its metadata <3)

**Comment by hashpad** [comment]
Done see: c25b563d25c3592044c7774f34a46ae38c2eda49
