### ISSUE TITLE
[CG] spacy --> get_candidates

### ISSUE THREAD

**Issue by kmdn** [kmdn/combining-linking-techniques#6]

**Comment by kmdn** [comment]
Weird. Tested with falcon2 CG API. Doubled candidates appear doubled,
single candidates are single there.

**Comment by hashpad** [comment]
Thank you for the response:
here is an example of the issue
![image](https://github.com/kmdn/combining-linking-techniques/assets/37782032/c821df20-f849-4efe-a193-a7af5c588616)
![image](https://github.com/kmdn/combining-linking-techniques/assets/37782032/8a24d23f-44c8-472f-a2a3-956ed4377f5e)
this means it's not a front end issue.
here is a dump of the json object sent by the python service:
{'uri': None, 'text': 'Berlin is a German city.', 'mentions': [{'mention': 'Berlin', 'assignment': None, 'offset': 0, 'detectionConfidence': 0.0, 'possibleAssignments': [{'score': 1.0, 'assignment': 'Berlin'}], 'originalMention': 'Berlin', 'originalWithoutStopwords': 'Berlin', 'scoreSecond': 0.0009006627798061597, 'types': 'Wikidata:Q515,Wikidata:Q486972,Schema:Place,Schema:City,DBpedia:Settlement,DBpedia:PopulatedPlace,DBpedia:Place,DBpedia:Location,DBpedia:City', 'support': 87107, 'logger': {'logName': 'structure.datatypes.MentionDBpediaSpotlight'}}, {'mention': 'German', 'assignment': None, 'offset': 12, 'detectionConfidence': 0.0, 'possibleAssignments': [{'score': 1.0, 'assignment': 'German'}], 'originalMention': 'German', 'originalWithoutStopwords': 'German', 'scoreSecond': 0.34304510213918743, 'types': 'Wikidata:Q6256,Schema:Place,Schema:Country,DBpedia:PopulatedPlace,DBpedia:Place,DBpedia:Location,DBpedia:Country', 'support': 222752, 'logger': {'logName': 'structure.datatypes.MentionDBpediaSpotlight'}}, {'mention': 'city', 'assignment': None, 'offset': 19, 'detectionConfidence': 0.0, 'possibleAssignments': [], 'originalMention': 'city', 'originalWithoutStopwords': 'city', 'scoreSecond': 0.11641020318384641, 'types': '', 'support': 22610, 'logger': {'logName': 'structure.datatypes.MentionDBpediaSpotlight'}}], 'componentId': 'MD1', 'pipelineType': 'MD'}

**Here is the relevant part of the json**
'possibleAssignments': [{'score': 1.0, 'assignment': 'German'}]

thank you in advance

**Comment by hashpad** [comment]
FYI: you can reproduce this even with (most likely any?) other candidate generator. 
example pipeline:  DBPediaSpotlight(MD) + DBPediaLookup(CG) with the text "Berlin is a German city.".

it seems like the results here are also duplicated.
